- hosts: all
  environment:
    DATABASE_URL: "{{ lookup('env', 'DATABASE_URL') }}"
    PASSWORD: "{{ lookup('env', 'PASSWORD') }}"
    USER: "{{ lookup('env', 'USER') }}"

  tasks:
    - name: "Roda: sudo apt update"
      become: yes
      apt:
        update_cache: yes
        upgrade: yes

    - name: "Instala pacotes"
      apt:
        name: "{{ item }}"
        state: latest
      become: yes # roda com sudo
      with_items:
        - default-jre
        - maven
        - mysql-server
        - python3-pycurl
        - python3-mysqldb

    #- name: "Instala pacotes"
    #  apt:
    #    name: "['default-jre', 'maven', 'mysql-server', 'python3-pycurl', 'python3-mysqldb']"
    #    state: latest
    #  become: yes # roda com sudo

    - name: "clone projeto"
      ansible.builtin.git:
        repo: 'https://github.com/torneseumprogramador/spring-web-youtube.git'
        dest: /home/ubuntu/projetoturma2/spring-web-youtube/
        clone: yes
        update: yes

    - name: "Lavanta serviço do mysql"
      become: yes
      service:
        name: mysql
        state: started

    #- name: "Criando senha root mysql"
    #  become: yes
    #  mysql_user:
    #    name: "{{ lookup('env', 'USER') }}"
    #    host: localhost
    #    password: "{{ lookup('env', 'PASSWORD') }}"
    #    priv: "*.*:ALL,GRANT"
    #    state: present

    - name: "Cria o banco de dados MySQL"
      mysql_db:
        name: SpringWebYoutube
        login_user: "{{ lookup('env', 'USER') }}"
        login_password: "{{ lookup('env', 'PASSWORD') }}"
        state: present


    #- name: Adicionar User no bashrc
    #  lineinfile: dest=~/.bashrc line='export USER={{ lookup('env', 'USER') }}' state=present

    #- name: Adicionar Pass no bashrc
    #  lineinfile: dest=~/.bashrc line='export PASSWORD="{{ lookup('env', 'PASSWORD') }}"' state=present

    #- name: Adicionar DB no bashrc
    #  lineinfile: dest=~/.bashrc line='export DATABASE_URL="{{ lookup('env', 'DATABASE_URL') }}"' state=present

    - name: Faz o package
      shell: "cd ~/projetoturma2/spring-web-youtube/ && mvn package"

    - name: Finaliza processo
      shell: "if lsof -t -i:8080 ; then sudo kill -9 $(lsof -t -i:8080); fi"

    - name: Inicia o projeto
      shell: "cd ~/projetoturma2/spring-web-youtube/ && nohup ./mvnw spring-boot:run &"

